// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctumvgygzquwibsmmpoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dW12Z3lnenF1d2lic21tcG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzkyODUsImV4cCI6MjA3MTU1NTI4NX0.ZqKK3UYq7t-SoWh6pJ5TkgenkMvSQgq3aYXtGflXMzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});